//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratoriaDatabaseEntities1 : DbContext
    {
        public LaboratoriaDatabaseEntities1()
            : base("name=LaboratoriaDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoggingUser> LoggingUser { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderServices> OrderServices { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ServiceWork> ServiceWork { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<StatusOrderService> StatusOrderService { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserOrderService> UserOrderService { get; set; }
        public virtual DbSet<Utilizer> Utilizer { get; set; }
        public virtual DbSet<Work> Work { get; set; }
    }
}
