//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderServices()
        {
            this.UserOrderService = new HashSet<UserOrderService>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ServiceWork ServiceWork { get; set; }
        public virtual StatusOrderService StatusOrderService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOrderService> UserOrderService { get; set; }
    }
}
