//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrderService
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int OrderServiceId { get; set; }
        public int UtilizerId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> TimeWork { get; set; }
    
        public virtual OrderServices OrderServices { get; set; }
        public virtual User User { get; set; }
        public virtual Utilizer Utilizer { get; set; }
    }
}
